server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/flowable
spring.datasource.driver=org.postgresql.Driver
spring.datasource.username=flowable
spring.datasource.password=flowable

spring.liquibase.enabled=true
spring.liquibase.change-log=config/liquibase/app-change-log.xml

# FlowableMailProperties
flowable.mail.server.host=localhost
flowable.mail.server.port=3025
flowable.mail.server.username=acme
flowable.mail.server.password=test
flowable.mail.server.properties.mail.smtp.starttls.enable=false
flowable.mail.server.properties.mail.smtp.starttls.required=false
flowable.mail.server.properties.mail.smtp.auth=true

# Flowable Security
flowable.idm.password-encoder=spring_bcrypt

## OpenAI
spring.ai.openai.enabled=true
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini

# App specific properties
acme.imap-inbound-adapter-url=imap://insurance.company%40localhost:test@localhost:3143/INBOX

spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.transport=http
spring.ai.mcp.server.name=cpr-flowable-mcp-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.mcp-endpoint=/mcp
spring.main.banner-mode=off

crp.flowable.mcp.enabled=true